name: Build iOS App

on: [workflow_dispatch] # Allows you to manually trigger the build

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build App
        # This builds a 'payload' which is what an IPA actually is
        run: |
            xcodebuild -scheme Test -sdk iphoneos -configuration Release clean build 
            CODE_SIGN_IDENTITY="" 
            CODE_SIGNING_REQUIRED=NO 
            CODE_SIGNING_ALLOWED=NO
            mkdir Payload
            mv build/Release-iphoneos/Test.app Payload/
            zip -r Test.ipa Payload


      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: app-binary
          path: YourAppName.ipa
